#===================================================================
# Production Configuration environment
#===================================================================

#Database configuration
MyServer:
  PORT: 8090

  Database:
    HOST: dpg-d24q1gp5pdvs73c4ko0g-a:5432
    DB_USERNAME: qr_menu_dtqy
    USER: root
    PASS: "L1Y8ZZFh8K73yu03Clp4yZqcKMsxvnm2"

# Redis configuration for production
spring:
  data:
    redis:
      host: red-d2850nvdiees73d9lhng
      port: 6379
      timeout: 2000ms
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 7200000 # 2 hours
      cache-null-values: false
